Update AspireDemoApi20250212102651.yml

diff --git a/.github/workflows/AspireDemoApi20250212102651.yml b/.github/workflows/AspireDemoApi20250212102651.yml
--- a/.github/workflows/AspireDemoApi20250212102651.yml
+++ b/.github/workflows/AspireDemoApi20250212102651.yml
@@ -45,19 +45,22 @@ jobs:
       - name: Publish application
         run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
 
-      - name: Install Swashbuckle CLI .NET Global Tool
-        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version 6.7.0
+      - name: Install Swashbuckle CLI .NET Local Tool
+        run: |
+          dotnet new tool-manifest
+          dotnet tool install Swashbuckle.AspNetCore.Cli --version 6.7.0
 
       - name: Ensure .NET Tools are in PATH
         run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
 
       - name: Verify Swashbuckle CLI Installation
-        run: dotnet tool list --global
+        run: dotnet tool list --local
 
       - name: Generate Open API Specification Document
         run: |
           export PATH="$HOME/.dotnet/tools:$PATH"
-          swagger tofile --output "${{ env.API_IMPORT_SPECIFICATION_PATH }}" "${{ env.API_IMPORT_DLL }}" ${{ env.API_IMPORT_VERSION }} --no-startup || (echo "Swagger generation failed" && exit 1)
+          dotnet tool restore
+          dotnet swagger tofile --output "${{ env.API_IMPORT_SPECIFICATION_PATH }}" "${{ env.API_IMPORT_DLL }}" ${{ env.API_IMPORT_VERSION }} --no-startup || (echo "Swagger generation failed" && exit 1)
 
       - name: Publish Artifacts
         uses: actions/upload-artifact@v4
